import { useMutation, gql } from '@apollo/client';

// Generated by https://quicktype.io
export interface DelNote {
  delNote: boolean;
}

export interface DelVar {
  // 被删除的文章的内容
  delNoteId: string;
}

const DEL_QL = gql`
  mutation DelNoteMutation($delNoteId: ID!) {
    delNote(id: $delNoteId)
  }
`;

const useDeleteNote = () => {
  const [delNote, { loading }] = useMutation<DelNote, DelVar>(DEL_QL);

  return {
    delNote,
    loading,
  };
};

export default useDeleteNote;
